sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t sirifromukraine/docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true sirifromukraine/docker-react npm run test